Improve function and fix bugs
qiayuanliao/galaxy_camera pull request #4
Opened 2022-03-29 02:46 UTC by ye-luo-xi-tui

2022-03-29 04:23 UTC, qiayuanliao commented
什么Function？

2022-03-29 04:29 UTC, qiayuanliao requested changes

2022-03-29 04:29 UTC, qiayuanliao commented on include/galaxy_camera.h
> +#define FIFO_SIZE 1023
不应该用宏

2022-03-29 04:29 UTC, qiayuanliao commented on launch/MER-139.launch
> +        <param name="image_height" value="900"/>
不应该把这个commit

2022-03-29 04:29 UTC, qiayuanliao commented on launch/MER-139.launch
> +    </node>
这部分不应该在这里，你这个只是一个相机驱动，应该在rm_track或者视觉的launch中，你这样写只是方便你测试而已

2022-03-29 04:29 UTC, qiayuanliao commented on launch/camera_imu.launch
> +</launch>
这个launch有可能不应该出现在这里，需要再讨论

2022-03-30 00:05 UTC, qiayuanliao requested changes

2022-03-30 00:05 UTC, qiayuanliao commented on src/galaxy_camera.cpp
> +  nh_.param("raising_filter_value", raising_filter_value_, 2000);
这个默认不是0吗？会影响到触发的，相当于电平需要持续2000us=2ms才会触发....

2022-03-30 01:35 UTC, ye-luo-xi-tui commented on src/galaxy_camera.cpp
> +  nh_.param("raising_filter_value", raising_filter_value_, 2000);
这个真不知道，没看过相机api。得问问周圳杰怎么想的了。不过这个参数一直被设为0。

2022-03-30 04:30 UTC, qiayuanliao approved these changes

2022-03-30 04:31 UTC, qiayuanliao approved these changes

2022-03-30 04:44 UTC, merged